version: '3.8'
services:
  pms-simulation:
    image: nehanawork1/pms-simulation:1.0
    container_name: pms-simulation
    ports:
      - "4000:8080"
    networks:
      - pms-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - pms-network

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: pms-usr
      POSTGRES_PASSWORD: pms-pw
      POSTGRES_DB: pms-db
    ports:
      - "5432:5432"
    networks:
      - pms-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Listeners
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Storage
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

      # Auto topic creation
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      # Idempotent producers
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      CLUSTER_ID: MkZkY0UzRUVGNDIzNDc5Qk  # generate via: base64 < /dev/urandom | tr -dc 'A-Z0-9' | head -c 22

    volumes:
      - ./data/kafka:/var/lib/kafka/data
    networks:
      - pms-network

networks:
  pms-network:
    driver: bridge
