server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://db-instance-pms.cvk4yqey0ex7.us-east-2.rds.amazonaws.com:5432/pms_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:PMS.2025}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
      
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 2147483647
      enable-idempotence: true
      max-in-flight-requests-per-connection: 1
      compression-type: lz4
      linger-ms: 10
    properties:
      delivery.timeout.ms: 120000
      request.timeout.ms: 60000

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

app:
  wsSimulatorUrl: ${WS_SIMULATOR_URL:ws://pms-simulation:8080/trade-websocket}


