server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pms-db
    username: pms-usr
    password: pms-pw
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      jdbc:
        time_zone: Asia/Kolkata
      hibernate.format_sql: false
      
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 2147483647
      enable-idempotence: true
      max-in-flight-requests-per-connection: 1
      compression-type: lz4
      linger-ms: 10
    properties:
      delivery.timeout.ms: 120000
      request.timeout.ms: 60000

  data:
    redis:
      host: localhost
      port: 6379

app:
  wsSimulatorUrl: ws://localhost:4000/trade-websocket


